### ISSUE TITLE
Unable to use this plugin on Windows 10

### ISSUE THREAD

**Issue by MrRaph** [BrainMaestro/cerebro-windows-system#2]
Hi,

I'm currently testing Cerebro on my Windows 10 64 bits laptop, and I was glade to see your plugin !

I used the cerebro command "plugins" to install it, but it didn't work.

Here's the errer message I can see in debug windows : 
`Error running plugin cerebro-windows-system TypeError: Cannot convert undefined or null to object(…)`

Cheers !
MrRaph_

**Comment by BrainMaestro** [comment]
Hey @MrRaph. What version of cerebro are you using?

**Comment by MrRaph** [comment]
I'm using 0.2.7, as in 0.2.6 I wasn't able to see your plugin in the list.
That was fixed by 0.2.7.

**Comment by BrainMaestro** [comment]
Alright. I just reproduced the bug. Already deployed a fix in `v0.2.1`. Check it out.

I'll close this, but if the problem reoccurs, feel free to reopen. Thanks.

**Comment by MrRaph** [comment]
Nice job ! :)
Thank you !

**Comment by BrainMaestro** [comment]
You're welcome! :)
