### ISSUE TITLE
where to put nircmd ?

### ISSUE THREAD

**Issue by muava12** [BrainMaestro/cerebro-windows-system#5]
![image](https://user-images.githubusercontent.com/3949553/94578977-838dd500-02a2-11eb-914f-9b5a73cdee25.png)

what should i do?
where is the path

**Comment by BrainMaestro** [comment]
hi @muava12. the `PATH` is an [environment variable](https://en.wikipedia.org/wiki/PATH_(variable)) that contains a list of folders where Windows will look for executables. it usually contains `C:\Program Files`, so maybe try there.

**Comment by muava12** [comment]
done, i tough it need to put manually..

but i can execute .exe file from nircmd to put the apps to the path, 

thanks
